default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: ^docs/

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: "v2.0.2"
    hooks:
      - id: autopep8

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: ^docs/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.950
    hooks:
      - id: mypy
        exclude: ^docs/

  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        exclude: |
          (?x)^(
              docs/.*|
              tests/.*|
          )$
        args: [--fail-under=80, --verbose]
