name: Code coverage

on:
  pull_request:
  push:
    branches: [main, master]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Generate Report
        run: |
          pip install --upgrade pip
          pip install coverage
          pip install .[test]

          coverage run -m unittest
          coverage report

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
