name: unittest

on:
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[test]
      - name: Get Testdata
        run: |
         git clone 'https://token:${{ secrets.GITLAB_TESTDATA }}@gitlab1.ptb.de/zimmer08/inhomcorr_testdata.git' testdata

      - name: Run unittest
        run: python -m unittest discover -s ./tests
